### ISSUE TITLE
About the 3n+4

### ISSUE THREAD

**Issue by hyichao** [liuzhuang13/DenseNetCaffe#14]
Hi Liu,

First congrads on the Best Paper Award.
I read the py codes of make_densenet.py, and I m pretty confused about the argument named depth

```
#change the line below to experiment with different setting
#depth -- must be 3n+4
#first_output -- #channels before entering the first dense block, set it to be comparable to growth_rate
#growth_rate -- growth rate
#dropout -- set to 0 to disable dropout, non-zero number to set dropout rate
def densenet(data_file, mode='train', batch_size=64, depth=40, first_output=16, growth_rate=12, dropout=0.2):
    data, label = L.Data(source=data_file, backend=P.Data.LMDB, batch_size=batch_size, ntop=2, 
              transform_param=dict(mean_value=128))
```
What's the meaning of this argument and why it must be 3*n+4, and what is n anyway?

**Comment by John1231983** [comment]
3 means number of dense block . 4 means 4 "convs" (BN-ReLU-Conv) in each block
Cheer

**Comment by NEU-Gou** [comment]
Seems the current .py code only implement the denseNet with 3 dense block (without bottle net layer). Therefore, the final number of convolution/innerProduct layers is 3 "block" * n "3x3 conv layer" + 1 "input conv layer" + 1 "innerProduct layer" + 2 "transition layer" = 3n+4

**Comment by liuzhuang13** [comment]
@hyichao  @John1231983   
@NEU-Gou 's answer is correct.

**Comment by hyichao** [comment]
@liuzhuang13 Got it now. And thanks to @NEU-Gou & @John1231983
