### ISSUE TITLE
Why the BatchNorm layer's lr_mult is 0?

### ISSUE THREAD

**Issue by insmod-he** [liuzhuang13/DenseNetCaffe#16]
Hi,liuzhuang13:
    Thanks for your great work. However I don't understand that in the train_densenet.prototxt, why the BatchNorm layer's lr_mult and decay_mult are set to 0? Can you explain it?

**Comment by liuzhuang13** [comment]
Sorry I cannot remember the reason for this. 
@Tongcheng, can you answer his question? Thanks a lot

**Comment by Tongcheng** [comment]
Hello @insmod-he ,  basically in caffe's original batchnorm, the BatchNorm didn't do the scale and bias part, it only does the variance and mean. So lr_mult and decay_mult actually refers to variance and mean, which should not be decayed or lt_mult etc.

**Comment by insmod-he** [comment]
Oh, I see. Thank you very much.
