### ISSUE TITLE
How to rename a layer

### ISSUE THREAD

**Issue by springzfx** [liuzhuang13/DenseNetCaffe#5]
what should I do, if  I want to  specify a layer name in  **make_densenet.py**?

**Comment by liuzhuang13** [comment]
Including a parameter "name" in the add layer function seems to work for me, like this:
`model = L.Convolution(data, name='Trump_layer', kernel_size=7, stride=2, num_output=nchannels, pad=3, bias_term=False, weight_filler=dict(type='msra'), bias_filler=dict(type='constant'))`

**Comment by springzfx** [comment]
I tried that, but it's not work in the correct way. It only replaces the name in the layer, and remains the auto_name in others layers which cite it as top or bottom.

**Comment by liuzhuang13** [comment]
Maybe try write a script to parse the prototxt file and replace the names?
