### ISSUE TITLE
Out of Memory on 1080

### ISSUE THREAD

**Issue by achaiah** [liuzhuang13/DenseNetCaffe#6]
Hi,

Have you tried running DenseNet on a GTX1080?  I'm not able to load it even with batch size 1 as the GPU runs out of memory.  Wondering if something may need to be tweaked in the Caffe implementation of the DenseNet.

**Comment by liuzhuang13** [comment]
Sorry we didn't try on GTX 1080. On our Titan X it works fine. Now I have access to two GTX1080s, I'll let you know when I have a chance to try it on.

**Comment by achaiah** [comment]
Out of curiosity, what was your batch size on Titan X?

**Comment by liuzhuang13** [comment]
It was 64 normally on one GPU. When I trained it with 4 GPUs to speed up, it was 16 on each GPU. So it is the same with the original paper

**Comment by achaiah** [comment]
64 in Caffe? That's strange. I'm running on 3x gtx1080 and can't even load 3.

**Comment by liuzhuang13** [comment]
64 or 128 are normal batch sizes used in many papers. DenseNet with 40 layer shouldn't consume a lot more memory than the 110 layer ResNet. Have you tried ResNets or other networks?

**Comment by achaiah** [comment]
Yeah I have no problems training 152 resnet. That's why I'm wondering why densenet is running out of memory.

**Comment by liuzhuang13** [comment]
What is the depth and growth rate of your DenseNet?

**Comment by achaiah** [comment]
I used the train_densnet.prototxt from this repo.

**Comment by liuzhuang13** [comment]
It is a 40 layer network with growth rate 12. Did you use it for ImageNet or CIFAR? It was designed for CIFAR datasets.

**Comment by liuzhuang13** [comment]
For ImageNet there should be a 4x spatial reduction at the first few layers. On CIFAR there wasn't

**Comment by achaiah** [comment]
I used it on the 17flowers dataset.  I'm not familiar enough with the network to tweak it by hand. Is there something I need to do to make it work for 17flowers (which is similar to ImageNet)?

**Comment by liuzhuang13** [comment]
How large is your input image size?

**Comment by achaiah** [comment]
I think I've tried 224px.  I have a set of 299px available as well.

**Comment by liuzhuang13** [comment]
Then you probably should replace the first 3*3 convolution in DenseNet, with a 7*7 convolution with stride 2 and 3 pixel padding, and a max pooling at the start. You can refer to the start part of ResNet-152.

**Comment by achaiah** [comment]
Thanks I'll try that

**Comment by achaiah** [comment]
Quick question... do you mean 
`Conv->BatchNorm->Pool->Conv2`
or 
`Conv->Pool->BatchNorm->Conv2`

**Comment by liuzhuang13** [comment]
See https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-101-deploy.prototxt line 8-59

Make sure to remove the first conv layer in the original DenseNet.

**Comment by achaiah** [comment]
Thanks for the pointers. I think I got the network correctly wired but my pooling layer seems to not fit. Any idea what to make kernel_size and stride for it?  I tried the defaults from Resnet-101 (kernel 3, stride 2) but they're not working.

```
Creating layer Convolution2
Creating Layer Convolution2
Convolution2 <- pool1
Convolution2 -> Convolution2
Setting up Convolution2
Top shape: 1 12 56 56 (37632)
Memory required for data: 20823044
Creating layer Dropout1
Creating Layer Dropout1
Dropout1 <- Convolution2
Dropout1 -> Dropout1
Setting up Dropout1
Top shape: 1 12 56 56 (37632)
Memory required for data: 20973572
Creating layer Concat1
Creating Layer Concat1
Concat1 <- Convolution1_ReLU1_0_split_1
Concat1 <- Dropout1
Concat1 -> Concat1
== bottom[i]->shape(j) (112 vs. 56) All inputs must have the same shape, except at concat_axis.
```

**Comment by liuzhuang13** [comment]
Sorry about the late response.

Can you share the prototxt file? "112 VS. 56" seems to indicate you didn't concatenate features of the same sizes

**Comment by achaiah** [comment]
I'm thinking the pooling layer needs to be adjusted but am not sure. Here's the file. The relevant stuff should be between the `################################` marks.  Thanks!

[DensenetEdited.txt](https://github.com/liuzhuang13/DenseNetCaffe/files/635017/DensenetEdited.txt)

**Comment by liuzhuang13** [comment]
[1207_densenet.txt](https://github.com/liuzhuang13/DenseNetCaffe/files/639361/1207_densenet.txt)

Here should be the right prototxt

You can visualize and see what's different using http://ethereon.github.io/netscope/#/editor

**Comment by achaiah** [comment]
Very interesting.  I made a small tweak (removing batch/relu/scale layers for first Convolution) that made a huge difference in convergence based on your original DenseNet.  Check out the before and after!

Trained with Adam it exhibits interesting jittery behavior, probably due to the dropouts in every block. I wonder if early blocks need dropouts at all or if they could be left out and produce more stable results.

![screen shot 2016-12-08 at 11 02 54 am](https://cloud.githubusercontent.com/assets/3967183/21019782/60b155f2-bd37-11e6-8082-2c7ac621f985.png)

![screen shot 2016-12-08 at 11 13 17 am](https://cloud.githubusercontent.com/assets/3967183/21019794/6a651b24-bd37-11e6-91a9-5600cf54b328.png)

**Comment by liuzhuang13** [comment]
So removing the first bn/scale/relu can stabalize the convergence and boost the performance? Interesting!

In our ImageNet models we trained using the first bn/scale/relu, because we borrowed the design from pre-act ResNets. In CIFAR there weren't. Our imageNet results are not as impressive as CIFAR results. If it was due to this, we might remove the first bn/scale/relu and have another try.

**Comment by liuzhuang13** [comment]
Can you share the prototxt after the removal? That might be more clear for us. Thanks!

**Comment by achaiah** [comment]
Sure thing, here it is.

[DensenetEdited.txt](https://github.com/liuzhuang13/DenseNetCaffe/files/640129/DensenetEdited.txt)

**Comment by achaiah** [comment]
Here's an interesting result with first four dropouts removed.  Keep in mind that this is just on the 17flowers dataset but it pushes the accuracy higher by over 2% on the top-1 recognition.  Your mileage may vary :)

![screen shot 2016-12-08 at 11 36 31 am](https://cloud.githubusercontent.com/assets/3967183/21020618/d50e79f4-bd3a-11e6-9304-fbd30c7df339.png)

**Comment by liuzhuang13** [comment]
That might be a interesting thing to try! I'm curious about how is DenseNet's results compared with other networks you've tried on your datasets?

**Comment by achaiah** [comment]
Haven't tried a lot of other datasets yet but so far I can't get any of the Inception models to train above 50-60% on top-5. And only one resnet (resnet18) goes above that as well.  However, here are a couple of successes:

Squeezenet
![squeezenet](https://cloud.githubusercontent.com/assets/3967183/21021017/74e0869c-bd3c-11e6-942e-17adeb1de451.png)

Resnet-18
![resnet18](https://cloud.githubusercontent.com/assets/3967183/21021028/7b516cbc-bd3c-11e6-89f9-825777cd6df0.png)

VGG16
![vgg16](https://cloud.githubusercontent.com/assets/3967183/21021034/81cdb1f4-bd3c-11e6-808e-90f7208b591c.png)

You'll notice they all have a much smoother progression curve than DenseNet. Again, probably because DenseNet gets a lot of reshuffling at every epoch so the search path is all over the place.  I've used Adam with DenseNet but AdaGrad with the others... I don't think that makes a big difference though.

**Comment by liuzhuang13** [comment]
So VGG and ResNet are all good on this datasets. Thanks!

**Comment by achbogga** [comment]
For people who might want to train for custom datasets with larger resolution images, please visit [https://github.com/achbogga/densenet_caffe_for_imagenet](https://github.com/achbogga/densenet_caffe_for_imagenet)
